#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=10

# Artifacts and the evidence transcript live in a work dir, never in the repo
# until the last stage decides the run is worth committing.
WORKDIR="${F39_WORKDIR:-${TMPDIR:-/tmp}/f39-incus-no-agent-boot}"
mkdir -p "$WORKDIR"
ENV_FILE="$WORKDIR/f39.env"                 # ask/write_env remember values across re-runs
EVIDENCE="$WORKDIR/f39-incus-no-agent-boot-$(date -u +%F).txt"
CODE_REPO="${CODE_REPO:-$HOME/projects/lnrent}"
SPEC_REPO="${SPEC_REPO:-$HOME/projects/lnrent-spec}"
VM="${F39_VM:-lnrent-f39}"
KEY="$WORKDIR/buyer_ed25519"
PROBE_PORT=8080
PASS=0; FAIL=0
VM_IP=""
KEYS=""
ALGOS=""
CHANNEL=""
URLHOST=""
# Hoisted: stage 10 repeats the process check after the reboot.
AGENT_RE='^(incus-agent|lxd-agent|qemu-ga|qemu-guest-agent)$'
# set -e is on. Every measurement below therefore ends in `|| true`: a probe
# that fails is a result this run must RECORD, never a reason to abort it.

# rec appends to the transcript as well as printing: stage() clears the screen,
# so scrollback is not evidence.
rec() { printf '  %s\n' "$1"; printf '%s\n' "$1" >> "$EVIDENCE"; }

check() { # check NAME EXPECTED ACTUAL
  if [[ "$2" == "$3" ]]; then PASS=$((PASS+1)); rec "PASS  $1  (= $3)"
  else FAIL=$((FAIL+1)); rec "FAIL  $1  (expected $2, got $3)"; fi
}

# run records the command itself alongside its output, so the evidence shows
# what was executed rather than what was meant.
#
# </dev/null is load-bearing: `incus init` parses stdin as a YAML instance
# config whenever stdin is not a TTY. Left inherited, anything feeding this
# wizard's stdin is silently read as instance config and the create fails
# with an empty error. Nothing run here ever wants the wizard's stdin.
run() {
  local out line
  rec "\$ $*"
  out="$("$@" </dev/null 2>&1)" || true
  # incus redraws progress with carriage returns, which lands in a file as one
  # enormous line. Keep only what followed the last CR: the final state.
  while IFS= read -r line; do rec "      ${line##*$'\r'}"; done <<< "$out"
}

# Every guest command: stdin closed and a hard wall-clock cap, so a VM that
# accepts TCP and then stalls cannot hang the run.
gssh() {
  timeout 20 ssh -n -i "$KEY" \
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -o GlobalKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=5 \
    -o BatchMode=yes -o PasswordAuthentication=no \
    -o KbdInteractiveAuthentication=no -o NumberOfPasswordPrompts=0 \
    "buyer@$VM_IP" "$@" 2>/dev/null
}

banner "F39: does Incus seed a VM with no guest agent?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What this run settles"
say "lnrent-spec F39 is CONTINGENT. The cloud-init half is already measured:"
say "a stock Debian 13 genericcloud image booted under plain QEMU with no agent"
say "of any kind, took a NoCloud seed, and answered a readiness probe."
say "  evidence: lnrent docs/evidence/f39-no-agent-boot-2026-09-20.txt (12/12)"
printf '\n'
say "One step is unrun, and it is the one ADR-0026 actually rests on:"
warn "does INCUS still attach the NoCloud seed with no agent share present?"
printf '\n'
note "Incus documents the agent-free path: a 'cloud-init:config' disk carries"
note "the seed, separately from the agent (which normally arrives over a 9p"
note "share named config, or as an optional 'agent:config' disk)."
note "This run measures whether that actually holds end to end."
printf '\n'
say "Stages 2-5 set up an Incus host and need your sudo and a fresh login."
say "Stages 6-10 run the measurement and write the evidence file."
note "transcript: $EVIDENCE"
: > "$EVIDENCE"
rec "=== F39 Incus no-agent boot run  $(date -u +%FT%TZ)"
rec "host: $(uname -srm)  |  $( (command -v nixos-version >/dev/null && nixos-version) || echo 'not NixOS')"
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "NixOS: enable Incus"
if command -v incus >/dev/null 2>&1; then
  say "incus is already on PATH; nothing to add."
  note "$(incus version 2>/dev/null | head -2 | tr '\n' ' ')"
  pause "Continue."
else
  say "Incus is not installed. On NixOS that is a declarative change:"
  printf '\n'
  cat <<'NIXBLOCK'
      virtualisation.incus.enable = true;
      users.extraGroups.incus-admin.members = [ "master" ];
NIXBLOCK
  printf '\n'
  note "incus does NOT require nftables (nixos/modules/virtualisation/incus.nix"
  note "only loads iptable_mangle when nftables is off), so this will not collide"
  note "with this box's networking.firewall.extraCommands."
  warn "It does add an incusbr0 bridge and iptables rules on a machine that"
  warn "already runs k3s and docker."
  printf '\n'
  if confirm "Add that block to /etc/nixos/configuration.nix (timestamped backup first)?"; then
    BAK="/etc/nixos/configuration.nix.bak-$(date +%Y%m%d-%H%M%S)"
    # The file is ONE top-level attrset. Appending past the final brace is a
    # syntax error, so insert before the last line that closes it.
    CLOSE="$(grep -n '^}[[:space:]]*$' /etc/nixos/configuration.nix | tail -1 | cut -d: -f1)"
    if [[ -z "$CLOSE" ]]; then
      warn "could not find the closing brace; add the block by hand"
      SKIPPED+=("the configuration.nix edit")
    elif sudo cp /etc/nixos/configuration.nix "$BAK" \
      && sudo sed -i "${CLOSE}i\\
\\  # Incus, for the lnrent-spec F39 no-agent VM boot run.\\
\\  virtualisation.incus.enable = true;\\
\\  users.extraGroups.incus-admin.members = [ \"master\" ];\\
" /etc/nixos/configuration.nix; then
      say "inserted before line $CLOSE; backup at $BAK"
    else
      warn "edit failed; add the block by hand"; SKIPPED+=("the configuration.nix edit")
    fi
  else
    say "Add those two lines to /etc/nixos/configuration.nix yourself."
    SKIPPED+=("the configuration.nix edit")
    pause "Done?"
  fi
fi

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Rebuild"
if command -v incusd >/dev/null 2>&1 || systemctl is-active --quiet incus 2>/dev/null; then
  say "incusd is already present; skipping the rebuild."
else
  say "Run this in another terminal (it wants your password and a few minutes):"
  printf '\n      %ssudo nixos-rebuild switch%s\n\n' "$BOLD" "$RESET"
  pause "Press Enter once it has finished."
fi
if systemctl is-active --quiet incus 2>/dev/null; then
  say "incus.service is active."
else
  warn "incus.service is not active yet. Check: systemctl status incus"
  confirm "Continue anyway?" || exit 1
fi

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Join incus-admin (this needs a NEW login)"
say "The socket is group incus-admin. Group membership is fixed at login, so"
say "this shell cannot gain it by itself, however many times you re-run me."
printf '\n'
if incus info >/dev/null 2>&1; then
  say "You can already talk to incusd. Nothing to do."
else
  step "Open a new terminal (or log out and back in), then re-run this wizard there."
  step "To test without logging out: newgrp incus-admin"
  printf '\n'
  note "check with: incus info"
  pause "Press Enter once 'incus info' works in this shell."
  if ! incus info >/dev/null 2>&1; then
    warn "still no access to the incus socket; stopping here rather than guessing."
    say "Re-run this wizard from a fresh login: $0"
    exit 1
  fi
fi

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Initialise Incus"
if incus storage list -f csv 2>/dev/null | grep -q .; then
  say "Incus already has a storage pool; skipping init."
else
  say "Incus needs one storage pool and one bridge before it can hold a VM."
  note "--minimal takes the defaults: a dir pool named 'default' plus incusbr0."
  warn "This creates a network bridge on this machine."
  printf '\n'
  if confirm "Run 'incus admin init --minimal'?"; then
    run incus admin init --minimal
  else
    say "Run 'incus admin init' yourself and answer its prompts."
    pause "Done?"
  fi
fi
INCUS_VERSION="$(incus version 2>/dev/null | awk '/[Ss]erver/{print $NF}' | head -1 || true)"
[[ -n "$INCUS_VERSION" ]] || INCUS_VERSION="$(incus version 2>/dev/null | head -1 || true)"
write_env INCUS_VERSION "$INCUS_VERSION"
rec "incus version: $INCUS_VERSION"
rec "kvm: $(test -e /dev/kvm && echo present || echo ABSENT)"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Pin the stock image"
say "F39 says 'stock curated image'. Use the same one the QEMU run pinned, so"
say "the two runs are comparable and the guest provably has no agent in it."
IMG_URL="https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
IMG_SHA="5754395abffb1d384d50f6d0945d46d1beb7be42a7e786e4fc4a6f27270ab16f"
BASE="$WORKDIR/debian-13-genericcloud-amd64.qcow2"
if [[ ! -f "$BASE" ]]; then
  say "fetching ~330 MB into $WORKDIR ..."
  curl -fSL --progress-bar -o "$BASE" "$IMG_URL" || { warn "download failed"; exit 1; }
fi
GOT_SHA="$(sha256sum "$BASE" | cut -d' ' -f1)"
rec "image:  debian-13-genericcloud-amd64.qcow2"
rec "sha256: $GOT_SHA"
if [[ "$GOT_SHA" != "$IMG_SHA" ]]; then
  warn "sha256 differs from the 2026-09-20 run ($IMG_SHA)."
  note "Debian republishes 'latest'. The run stays valid; the new digest is recorded."
fi
write_env F39_IMAGE_SHA256 "$GOT_SHA"
say "Importing it as an Incus VM image (no agent inside it)."
printf 'architecture: x86_64\ncreation_date: %s\nproperties:\n  description: Debian 13 genericcloud, stock, no incus-agent\n  os: debian\n  release: trixie\n' "$(date +%s)" > "$WORKDIR/metadata.yaml"
( cd "$WORKDIR" && tar -cJf metadata.tar.xz metadata.yaml )
incus image delete f39-stock </dev/null >/dev/null 2>&1 || true
if run incus image import "$WORKDIR/metadata.tar.xz" "$BASE" --alias f39-stock \
   && incus image info f39-stock >/dev/null 2>&1; then
  F39_IMAGE="f39-stock"; F39_VARIANT="A: stock image, no agent binary present"
  say "imported as f39-stock."
else
  warn "Incus would not import the stock qcow2."
  say "Fall back to images:debian/13/cloud, which SHIPS the agent, and mask its"
  say "loader instead. F39 and the astra review both say these prove different"
  say "things: removed-share satisfies SEC-45, a masked loader does not."
  confirm "Use the fallback (and record it as the weaker variant)?" || exit 1
  F39_IMAGE="images:debian/13/cloud"; F39_VARIANT="B: agent in image, loader masked (does NOT satisfy SEC-45)"
fi
write_env F39_IMAGE "$F39_IMAGE"
rec "variant: $F39_VARIANT"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Build the VM with no agent share"
ssh-keygen -t ed25519 -N '' -f "$KEY" -q <<< y >/dev/null 2>&1 || true
BUYER_PUB="$(cat "$KEY.pub")"
cat > "$WORKDIR/user-data" <<EOF
#cloud-config
users:
  - name: buyer
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - $BUYER_PUB
write_files:
  - path: /etc/lnrent-workload.conf
    permissions: '0644'
    content: |
      workload=probe-demo
      seeded_by=lnrent-seed-fragment
  - path: /etc/systemd/system/lnrent-probe.service
    permissions: '0644'
    content: |
      [Unit]
      Description=lnrent readiness probe target
      After=network.target
      [Service]
      # --bind :: is load-bearing: http.server defaults to 0.0.0.0, IPv4 only,
      # and incusbr0 gives an agent-free guest only a v6 (SLAAC) address, so
      # the default bind makes the probe unreachable on the address we have.
      ExecStart=/usr/bin/python3 -m http.server $PROBE_PORT --bind :: --directory /etc
      Restart=always
      [Install]
      WantedBy=multi-user.target
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, --now, lnrent-probe.service ]
EOF
say "Buyer public key first, then the Recipe's Seed fragment: the VMH-31 order."
incus delete -f "$VM" </dev/null >/dev/null 2>&1 || true
run incus init "$F39_IMAGE" "$VM" --vm
incus config set "$VM" cloud-init.user-data - < "$WORKDIR/user-data" \
  && rec "\$ incus config set $VM cloud-init.user-data - < user-data   [ok]" \
  || { warn "could not set cloud-init.user-data"; rec "FAIL  set-cloud-init-user-data"; FAIL=$((FAIL+1)); }
say "security.guestapi=false removes /dev/incus from the guest."
run incus config set "$VM" security.guestapi=false
say "The agent-free seed path, straight from the Incus docs:"
run incus config device add "$VM" cloud-init disk source=cloud-init:config
[[ "$F39_IMAGE" == "images:"* ]] && run incus config set "$VM" cloud-init.vendor-data "#cloud-config
bootcmd:
  - [ systemctl, mask, --now, incus-agent.service ]"
say "Recording the expanded device configuration, which is what tells a reader"
say "whether an agent share was attached at all (SEC-45)."
run incus config show "$VM" --expanded
pause "Review the devices above. Enter to boot."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Boot, and find it without the agent"
run incus start "$VM"
say "Incus learns a VM's address FROM the agent. With no agent, 'incus list'"
say "should show none, and the DHCP lease is the only way to find it."
run incus list "$VM"
for _ in $(seq 1 60); do
  LEASES="$(incus network list-leases incusbr0 -f csv 2>/dev/null || true)"
  # incusbr0 hands out both a v4 and a v6 lease. Prefer v4: it keeps this run
  # comparable with the QEMU one, and v6 needs bracketing in URLs.
  VM_IP="$(awk -F, -v v="$VM" '$1==v && $3 ~ /\./ {print $3}' <<< "$LEASES" | head -1 || true)"
  [[ -n "$VM_IP" ]] || VM_IP="$(awk -F, -v v="$VM" '$1==v{print $3}' <<< "$LEASES" | head -1 || true)"
  [[ -n "$VM_IP" ]] && break
  sleep 5
done
# A bare IPv6 literal in a URL is malformed; curl returns 000. Bracket it.
case "$VM_IP" in *:*) URLHOST="[$VM_IP]" ;; *) URLHOST="$VM_IP" ;; esac
if [[ -z "$VM_IP" ]]; then
  rec "FAIL  no DHCP lease for $VM after 300s"; FAIL=$((FAIL+1))
  run incus console "$VM" --show-log
  warn "No lease. If the guest never got the seed, that IS F39's answer: record it."
  pause "Enter to go to the verdict."
else
  rec "lease: $VM ->  $VM_IP  (from incus network list-leases, not the agent)"
  say "address $VM_IP"
  for _ in $(seq 1 60); do
    [[ "$(gssh hostname 2>/dev/null)" == "$VM" ]] && break
    sleep 5
  done
  check "guest-identifies-as-this-run" "$VM" "$(gssh hostname 2>/dev/null)"
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Prove no agent, and that the seed still landed"
if [[ -n "$VM_IP" ]]; then
  say "(d) host keys over an SSH key exchange, before trusting anything (ADR-0028 §3)"
  # ADR-0028 §3 pins the canonical `algorithm base64` form, so the stability
  # check must carry the key material. Comparing $2 alone compares algorithm
  # NAMES: every host key could rotate and the check would still pass.
  # Filter to actual key lines: ssh-keyscan also emits a banner line whose
  # second field is the version string, which otherwise pollutes the compare.
  KEYS="$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2" "$3}' | sort -u | tr '\n' '|' || true)"
  ALGOS="$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2}' | sort -u | tr '\n' ' ' || true)"
  check "host-keys-readable-over-network" "yes" "$([[ -n "$KEYS" ]] && echo yes || echo no)"
  rec "      algorithms: $ALGOS"
  rec "      host-key fingerprints: $(printf '%s' "$KEYS" | tr '|' '\n' | grep -c . || true) key(s) pinned"

  say "(c) readiness probe on the unit's own private address"
  check "readiness-probe-http" "200" \
    "$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://$URLHOST:$PROBE_PORT/lnrent-workload.conf")"

  say "(a) the seed landed: buyer key, then the Seed fragment"
  check "buyer-key-login" "buyer" "$(gssh 'id -un')"
  check "seed-fragment-applied" "1" "$(gssh 'grep -c seeded_by=lnrent-seed-fragment /etc/lnrent-workload.conf')"
  rec "      cloud-init: $(gssh 'cloud-init status' | head -1)"
  rec "      datasource: $(gssh 'sudo cloud-init query platform')"

  say "(b) no agent. A refused exec alone does not prove this, so look inside too."
  run incus exec "$VM" -- true
  check "incus-exec-refused" "no" "$(incus exec "$VM" -- true </dev/null >/dev/null 2>&1 && echo yes || echo no)"
  check "no-dev-incus-in-guest" "0" "$(gssh 'ls -d /dev/incus 2>/dev/null | wc -l')"
  check "no-agent-process" "0" "$(gssh "ps -eo comm= | grep -cE '$AGENT_RE' || true")"
  check "no-agent-binary" "0" "$(gssh 'command -v incus-agent lxd-agent qemu-ga 2>/dev/null | wc -l')"
  check "no-agent-unit-running" "0" "$(gssh 'systemctl is-active incus-agent.service 2>/dev/null | grep -c ^active || true')"
  # SEC-45 is a separate question from "does an agent run", and it is the one
  # that governs the tier bound: "no guest agent share attached to a unit
  # claiming tier 1 or above". Incus builds the agent's virtio-serial channel
  # into the qemu command line, so it is NOT an `incus config device` entry
  # and cannot be removed with `incus config device remove`. Counted on its
  # own, because a failure here does not impeach the seeding result above.
  # The guest's mount list cannot answer SEC-45: a stock image has no agent
  # udev rules, so it never mounts the share and reports 0 whether or not one
  # is attached. Read the generated qemu config instead — Incus adds the config
  # and agent 9p drives there, outside the `incus config device` list, so the
  # fixtured device scan cannot see them either.
  QCONF="/run/incus/$VM/qemu.conf"
  if [[ -r "$QCONF" ]]; then
    AGENT_SHARE="$(grep -c 'mount_tag = "agent"' "$QCONF" || true)"
    rec "      qemu.conf agent 9p share attached: $AGENT_SHARE"
    rec "      qemu.conf 9p mount_tags: $(grep -o 'mount_tag = "[a-z]*"' "$QCONF" | tr '\n' ' ' || true)"
    rec "      agent share path: $(awk '/\[fsdev "qemu_agent"\]/,/^$/' "$QCONF" | grep '^path' || true)"
    check "no-agent-share-in-qemu-config" "0" "$AGENT_SHARE"
  else
    AGENT_SHARE="unknown"
    rec "      qemu.conf not readable at $QCONF; attachment UNMEASURED"
  fi
  # ADR-0026's stated worry is "a host-provided share the tenant can read, stop
  # or impersonate". Test that directly -- and record WHY it fails, because a
  # failed mount here is a property of the guest KERNEL, not of the hypervisor
  # or of anything the Operator declared. Debian's genericcloud flavour ships
  # no 9p modules; an image whose kernel has them can mount the very same
  # attached share, with no change to the Incus configuration.
  NINEP="$(gssh 'grep -c 9p /proc/filesystems || true' || true)"
  rec "      guest kernel: $(gssh 'uname -r' || true)"
  rec "      guest 9p filesystem support: ${NINEP:-unknown}"
  MOUNTED="$(gssh 'sudo mkdir -p /mnt/f39a && sudo mount -t 9p -o trans=virtio,version=9p2000.L,ro agent /mnt/f39a 2>/dev/null && echo yes || echo no' || true)"
  rec "      tenant mount of tag 'agent': ${MOUNTED:-unknown} (contents: $(gssh 'ls /mnt/f39a 2>/dev/null | tr "\n" " "' || true))"
  if [[ "${NINEP:-0}" == "0" ]]; then
    rec "NOTE  the tenant could not read the attached share only because this"
    rec "      image's kernel lacks 9p; that is an image property no requirement"
    rec "      in this set records or checks."
  fi
  gssh 'sudo umount /mnt/f39a 2>/dev/null; sudo rmdir /mnt/f39a 2>/dev/null' >/dev/null 2>&1 || true

  CHANNEL="$(gssh 'ls /dev/virtio-ports/ 2>/dev/null | grep -c linuxcontainers || true' || true)"
  CHANNEL="${CHANNEL:-unknown}"
  rec "      agent channel attached by hypervisor: $CHANNEL  (/dev/virtio-ports/org.linuxcontainers.*)"
  rec "      9p config share mounted in guest: $(gssh 'mount -t 9p 2>/dev/null | wc -l') mount(s)"
  rec "      all virtio-ports: $(gssh 'ls /dev/virtio-ports/ 2>/dev/null | tr "\n" " "')"
  if [[ "$CHANNEL" == "0" ]]; then
    rec "SEC-45  satisfiable: no agent share attached"
  else
    rec "SEC-45  NOT satisfiable: the agent channel is attached regardless of the image"
  fi

  say "negative control: show the detectors can fail"
  gssh 'sudo cp /bin/sleep /usr/local/bin/incus-agent && sudo sh -c "nohup /usr/local/bin/incus-agent 60 >/dev/null 2>&1 &"' >/dev/null 2>&1
  sleep 2
  NEG="$(gssh "ps -eo comm= | grep -cE '$AGENT_RE' || true" || true)"
  if [[ "${NEG:-0}" -ge 1 ]]; then PASS=$((PASS+1)); rec "PASS  negative-control: planted agent process detected (= $NEG)"
  else FAIL=$((FAIL+1)); rec "FAIL  negative-control: planted agent process NOT detected"; fi
  gssh 'sudo pkill -x incus-agent; sudo rm -f /usr/local/bin/incus-agent' >/dev/null 2>&1
else
  rec "skipped the proofs: never reached the guest"
fi
pause "Enter to reboot and repeat."

# ── 10 ────────────────────────────────────────────────────────────────────
stage "Reboot, then the verdict"
if [[ -n "$VM_IP" ]]; then
  run incus restart "$VM"
  for _ in $(seq 1 60); do [[ "$(gssh hostname 2>/dev/null)" == "$VM" ]] && break; sleep 5; done
  check "readiness-probe-after-reboot" "200" \
    "$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://$URLHOST:$PROBE_PORT/lnrent-workload.conf")"
  check "host-keys-stable-across-reboot" "$KEYS" \
    "$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2" "$3}' | sort -u | tr '\n' '|')"
  # Repeat the whole no-agent set, not just /dev/incus: checking one of four
  # after a reboot does not re-establish the other three.
  check "no-dev-incus-after-reboot" "0" "$(gssh 'ls -d /dev/incus 2>/dev/null | wc -l')"
  check "no-agent-process-after-reboot" "0" "$(gssh "ps -eo comm= | grep -cE '$AGENT_RE' || true")"
  check "no-agent-binary-after-reboot" "0" "$(gssh 'command -v incus-agent lxd-agent qemu-ga 2>/dev/null | wc -l')"
  check "incus-exec-refused-after-reboot" "no" \
    "$(incus exec "$VM" -- true </dev/null >/dev/null 2>&1 && echo yes || echo no)"
fi
rec "=== $PASS passed, $FAIL failed"
rec "variant proven: $F39_VARIANT"
printf '\n'
# Two independent questions. Collapsing them into one pass/fail was wrong:
# the seeding claim can hold while the tier bound still stands, and that is
# in fact what this run measures.
if [[ "$FAIL" -eq 0 && -n "$VM_IP" && "$F39_IMAGE" == "f39-stock" ]]; then
  say "${BOLD}ADR-0026 / VMH-35: PROVEN.${RESET} Incus seeded a stock image that carries"
  say "no agent at all, from a cloud-init:config disk, and nothing agent-like"
  say "ran in the guest. 'Curated images ship without a guest agent' can be a MUST."
  if [[ "$CHANNEL" == "0" ]]; then
    say "${BOLD}SEC-45: also satisfied.${RESET} No agent share attached. VMH-7's tier bound lifts."
    F39_RESULT="closes-fully"
  else
    printf '\n'
    say "${BOLD}SEC-45: NOT satisfied, and VMH-7's tier bound STANDS.${RESET}"
    say "Incus attaches the agent's virtio-serial channel"
    say "(/dev/virtio-ports/org.linuxcontainers.incus) to every VM from the qemu"
    say "command line. It is not an 'incus config device' entry, so no device"
    say "removal takes it away. Nothing in the guest listens on it here, but"
    say "SEC-45 asks whether the share is ATTACHED, not whether it is used."
    say "So F39 closes on its own terms and hands VMH-7 a NEW reason to stand:"
    say "not 'the image loads an agent' but 'the hypervisor always offers one'."
    F39_RESULT="seeding-proven-tier-bound-stands"
  fi
else
  say "${BOLD}F39 stays contingent.${RESET} $FAIL check(s) failed. That is a result, not a"
  say "waste: the closing move becomes rebuilding curated images agent-free."
  F39_RESULT="contingent"
fi
write_env F39_RESULT "$F39_RESULT"
printf '\n'
if confirm "Delete the VM $VM?"; then run incus delete -f "$VM"; else note "left running: incus delete -f $VM"; fi
printf '\n'
say "The evidence must live in version control. lnrent-spec/.gitignore has"
say ".context/, so a record written there cannot be cited by F39."
printf '\n      %scp %s \\\n        %s/docs/evidence/%s\n' \
  "$BOLD" "$EVIDENCE" "$CODE_REPO" "$(basename "$EVIDENCE")$RESET"
printf '      cd %s && git checkout f39-no-agent-boot && git add docs/evidence/\n\n' "$CODE_REPO"
note "then cite it from $SPEC_REPO/17-open-findings.md F39"

finish
