#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────


TOTAL_STAGES=8

# The libvirt leg of lnrent-spec F39/F66. Same image, same checks and same
# check NAMES as f39-incus-no-agent-boot.sh, so the two evidence files can be
# read side by side. The question here is not "what does the backend force on
# me" but "what does it add beyond what I declared".
WORKDIR="${F39_WORKDIR:-${TMPDIR:-/tmp}/f39-libvirt-no-agent-boot}"
mkdir -p "$WORKDIR"
ENV_FILE="$WORKDIR/f39.env"
EVIDENCE="$WORKDIR/f39-libvirt-no-agent-boot-$(date -u +%F).txt"
VM="${F39_VM:-lnrent-f39-libvirt}"
KEY="$WORKDIR/buyer_ed25519"
PROBE_PORT=8080
PASS=0; FAIL=0
VM_IP=""; KEYS=""; ALGOS=""; URLHOST=""
AGENT_RE='^(incus-agent|lxd-agent|qemu-ga|qemu-guest-agent)$'
# set -e is on; every measurement ends in `|| true` so a failing probe is
# recorded rather than aborting the run.

rec() { printf '  %s\n' "$1"; printf '%s\n' "$1" >> "$EVIDENCE"; }
check() {
  if [[ "$2" == "$3" ]]; then PASS=$((PASS+1)); rec "PASS  $1  (= $3)"
  else FAIL=$((FAIL+1)); rec "FAIL  $1  (expected $2, got $3)"; fi
}
run() {
  local out line
  rec "\$ $*"
  out="$("$@" </dev/null 2>&1)" || true
  while IFS= read -r line; do rec "      ${line##*$'\r'}"; done <<< "$out"
}
gssh() {
  timeout 20 ssh -n -i "$KEY" \
    -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null \
    -o GlobalKnownHostsFile=/dev/null -o LogLevel=ERROR -o ConnectTimeout=5 \
    -o BatchMode=yes -o PasswordAuthentication=no \
    -o KbdInteractiveAuthentication=no -o NumberOfPasswordPrompts=0 \
    "buyer@$VM_IP" "$@" 2>/dev/null
}

banner "F39/F66: does libvirt attach an agent share?"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "What this run settles"
say "The Incus run (2026-09-21) found an agent 9p share attached to every VM"
say "from the hypervisor's own start path, where the device list cannot see it."
printf '\n'
say "This asks the same question of libvirt, on the same box, the same kernel"
say "and the same pinned image, so the answer is a comparison and not a vibe."
printf '\n'
warn "libvirt builds what the domain XML declares, so a clean result here is"
warn "only meaningful if we ALSO diff the generated qemu command line against"
warn "what we asked for. That is the check the Incus run was missing."
note "transcript: $EVIDENCE"
: > "$EVIDENCE"
rec "=== F39/F66 libvirt no-agent boot run  $(date -u +%FT%TZ)"
rec "host: $(uname -srm)  |  $( (command -v nixos-version >/dev/null && nixos-version) || echo 'not NixOS')"
pause "Ready?"

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Preflight"
if ! command -v virsh >/dev/null 2>&1; then
  warn "virsh not on PATH; this stage cannot continue."; exit 1
fi
run virsh version
systemctl is-active --quiet libvirtd 2>/dev/null && say "libvirtd active" || warn "libvirtd not active"
# The default NAT network gives the guest an address and a DHCP lease we can
# read without any agent -- libvirt's equivalent of incusbr0.
virsh net-start default >/dev/null 2>&1 || true
virsh net-autostart default >/dev/null 2>&1 || true
run virsh net-list --all
EMU="$(ls /run/libvirt/nix-emulators/qemu-system-x86_64 2>/dev/null || command -v qemu-system-x86_64 || true)"
rec "emulator: $EMU"
[[ -n "$EMU" ]] || { warn "no qemu emulator found"; exit 1; }
rec "libvirt: $(virsh version 2>/dev/null | tr '\n' ' ' || true)"
pause "Continue."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Pin the same stock image"
IMG_URL="https://cloud.debian.org/images/cloud/trixie/latest/debian-13-genericcloud-amd64.qcow2"
IMG_SHA="5754395abffb1d384d50f6d0945d46d1beb7be42a7e786e4fc4a6f27270ab16f"
BASE="$WORKDIR/debian-13-genericcloud-amd64.qcow2"
# Reuse the Incus leg's download when it is already here: same digest, and it
# keeps the two legs provably on one image.
for cand in "/tmp/f39-incus-no-agent-boot/debian-13-genericcloud-amd64.qcow2" \
            "${TMPDIR:-/tmp}/f39-incus-no-agent-boot/debian-13-genericcloud-amd64.qcow2"; do
  [[ -f "$BASE" ]] && break
  [[ -f "$cand" ]] && { cp "$cand" "$BASE"; say "reused the Incus leg's image"; }
done
if [[ ! -f "$BASE" ]]; then
  say "fetching ~330 MB ..."
  curl -fSL --progress-bar -o "$BASE" "$IMG_URL" || { warn "download failed"; exit 1; }
fi
GOT_SHA="$(sha256sum "$BASE" | cut -d' ' -f1)"
rec "image:  debian-13-genericcloud-amd64.qcow2"
rec "sha256: $GOT_SHA"
[[ "$GOT_SHA" == "$IMG_SHA" ]] || warn "digest differs from the Incus leg's ($IMG_SHA)"
write_env F39_IMAGE_SHA256 "$GOT_SHA"
OVL="$WORKDIR/overlay.qcow2"
rm -f "$OVL"
run qemu-img create -q -f qcow2 -b "$BASE" -F qcow2 "$OVL" 8G

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Build the NoCloud seed"
ssh-keygen -t ed25519 -N '' -f "$KEY" -q <<< y >/dev/null 2>&1 || true
BUYER_PUB="$(cat "$KEY.pub")"
cat > "$WORKDIR/user-data" <<EOF
#cloud-config
users:
  - name: buyer
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - $BUYER_PUB
write_files:
  - path: /etc/lnrent-workload.conf
    permissions: '0644'
    content: |
      workload=probe-demo
      seeded_by=lnrent-seed-fragment
  - path: /etc/systemd/system/lnrent-probe.service
    permissions: '0644'
    content: |
      [Unit]
      Description=lnrent readiness probe target
      After=network.target
      [Service]
      ExecStart=/usr/bin/python3 -m http.server $PROBE_PORT --bind :: --directory /etc
      Restart=always
      [Install]
      WantedBy=multi-user.target
runcmd:
  - [ systemctl, daemon-reload ]
  - [ systemctl, enable, --now, lnrent-probe.service ]
EOF
printf 'instance-id: lnrent-f39-libvirt-0001\nlocal-hostname: %s\n' "$VM" > "$WORKDIR/meta-data"
say "Buyer public key first, then the Recipe's Seed fragment (VMH-31 order)."
run cloud-localds "$WORKDIR/seed.iso" "$WORKDIR/user-data" "$WORKDIR/meta-data"

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Declare the domain, and declare nothing else"
# Exactly three devices plus a console. No <channel>, no <filesystem>, no
# <serial> agent port. Whatever shows up beyond this is libvirt's doing.
cat > "$WORKDIR/domain.xml" <<EOF
<domain type='kvm'>
  <name>$VM</name>
  <memory unit='MiB'>1024</memory>
  <vcpu>2</vcpu>
  <!-- firmware='efi' is required, and it also makes this leg firmware-identical
       to the Incus leg, which boots every VM under OVMF. Under SeaBIOS this
       image loads GRUB, prints "Booting Debian GNU/Linux" and resets in a
       loop with no kernel output at all. -->
  <os firmware='efi'><type arch='x86_64' machine='q35'>hvm</type></os>
  <features><acpi/><apic/></features>
  <cpu mode='host-passthrough' check='none'/>
  <devices>
    <emulator>$EMU</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='$OVL'/>
      <target dev='vda' bus='virtio'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='$WORKDIR/seed.iso'/>
      <target dev='sda' bus='sata'/>
      <readonly/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <model type='virtio'/>
    </interface>
    <serial type='file'><source path='$WORKDIR/console.log'/><target port='0'/></serial>
  </devices>
</domain>
EOF
rec "declared devices: disk(virtio), cdrom(seed), interface(virtio), console"
rec "declared NO <channel>, NO <filesystem>, NO agent port"
virsh destroy "$VM" >/dev/null 2>&1 || true
virsh undefine "$VM" --nvram >/dev/null 2>&1 || true
run virsh define "$WORKDIR/domain.xml"
run virsh start "$VM"

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "What did libvirt actually build?"
sleep 5
# This plays the same role /run/incus/<vm>/qemu.conf played for the Incus leg.
# Read the LIVE argv from /proc rather than parsing the log: libvirt writes
# the command as backslash-continued lines, so a line-oriented grep captures
# the emulator path alone and every "count of forbidden tokens" then comes
# back 0 -- a false green of exactly the kind this run exists to catch.
QPID="$(cat "/run/libvirt/qemu/$VM.pid" 2>/dev/null || true)"
CMDLINE=""
if [[ -n "$QPID" && -r "/proc/$QPID/cmdline" ]]; then
  CMDLINE="$(tr '\0' ' ' < "/proc/$QPID/cmdline" || true)"
  rec "qemu argv read from /proc/$QPID/cmdline (${#CMDLINE} chars)"
else
  QLOG="/var/log/libvirt/qemu/$VM.log"
  CMDLINE="$(sed -n "/starting up/,/^$/p" "$QLOG" 2>/dev/null | tr '\n' ' ' || true)"
  rec "qemu argv read from $QLOG (${#CMDLINE} chars)"
fi
# A short capture is a failed measurement, not a clean one.
if (( ${#CMDLINE} < 200 )); then
  rec "FAIL  qemu-argv-captured  (only ${#CMDLINE} chars; the token counts below would be vacuous)"
  FAIL=$((FAIL+1))
  CMDLINE=""
fi
if [[ -n "$CMDLINE" ]]; then
  check "qemu-argv-captured" "yes" "yes"
  # grep -c counts LINES, and the argv is one line, so it would report 1 for
  # any number of hits. Count occurrences.
  SHARE="$(printf '%s' "$CMDLINE" | grep -o 'virtfs\|fsdev\|mount_tag' | wc -l || true)"
  CHAN="$(printf '%s' "$CMDLINE" | grep -o 'org.qemu.guest_agent\|org.linuxcontainers\|virtserialport' | wc -l || true)"
  rec "      agent-share tokens (virtfs/fsdev/mount_tag): ${SHARE:-0}"
  rec "      agent-channel tokens (guest_agent/virtserialport): ${CHAN:-0}"
  rec "      chardevs: $(printf '%s' "$CMDLINE" | grep -o '\-chardev [^ ]*' | tr '\n' ' ' || true)"
  check "no-agent-share-in-qemu-cmdline" "0" "${SHARE:-0}"
  check "no-agent-channel-in-qemu-cmdline" "0" "${CHAN:-0}"
else
  rec "      attachment UNMEASURED: no usable argv, so nothing below is evidence"
fi
run virsh dumpxml "$VM"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Boot, reach it, and prove no agent"
MAC="$(virsh dumpxml "$VM" 2>/dev/null | grep -o "mac address='[^']*'" | head -1 | cut -d\' -f2 || true)"
rec "mac: $MAC"
for _ in $(seq 1 60); do
  VM_IP="$(virsh net-dhcp-leases default 2>/dev/null | awk -v m="$MAC" '$0 ~ m {print $5}' | cut -d/ -f1 | head -1 || true)"
  [[ -n "$VM_IP" ]] && break
  sleep 5
done
case "$VM_IP" in *:*) URLHOST="[$VM_IP]" ;; *) URLHOST="$VM_IP" ;; esac
if [[ -z "$VM_IP" ]]; then
  rec "FAIL  no DHCP lease after 300s"; FAIL=$((FAIL+1))
  rec "      guest console tail:"
  while IFS= read -r l; do rec "        $l"; done < <(tail -20 "$WORKDIR/console.log" 2>/dev/null || true)
  rec "      leases: $(virsh net-dhcp-leases default 2>&1 | tail -3 | tr '\n' ' ' || true)"
  rec "      virbr0: $(ip -brief addr show virbr0 2>&1 || true)"
  rec "      NOTE a NixOS host needs networking.firewall.trustedInterfaces = [ \"virbr0\" ];"
  rec "      libvirt's rules live in table ip libvirt_network and do not override"
  rec "      the inet nixos-fw input drop. Incus installs its own inet accepts."
else
  rec "lease: $VM -> $VM_IP  (from virsh net-dhcp-leases, no agent)"
  for _ in $(seq 1 60); do [[ "$(gssh hostname 2>/dev/null)" == "$VM" ]] && break; sleep 5; done
  check "guest-identifies-as-this-run" "$VM" "$(gssh hostname 2>/dev/null)"
  KEYS="$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2" "$3}' | sort -u | tr '\n' '|' || true)"
  ALGOS="$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2}' | sort -u | tr '\n' ' ' || true)"
  check "host-keys-readable-over-network" "yes" "$([[ -n "$KEYS" ]] && echo yes || echo no)"
  rec "      algorithms: $ALGOS"
  check "readiness-probe-http" "200" \
    "$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://$URLHOST:$PROBE_PORT/lnrent-workload.conf")"
  check "buyer-key-login" "buyer" "$(gssh 'id -un')"
  check "seed-fragment-applied" "1" "$(gssh 'grep -c seeded_by=lnrent-seed-fragment /etc/lnrent-workload.conf')"
  rec "      cloud-init: $(gssh 'cloud-init status' | head -1)"
  rec "      datasource: $(gssh 'sudo cloud-init query platform')"
  check "no-agent-process" "0" "$(gssh "ps -eo comm= | grep -cE '$AGENT_RE' || true")"
  check "no-agent-binary" "0" "$(gssh 'command -v incus-agent lxd-agent qemu-ga 2>/dev/null | wc -l')"
  check "no-virtio-ports-in-guest" "0" "$(gssh 'ls /dev/virtio-ports/ 2>/dev/null | wc -l')"
  rec "      virtio-ports seen: $(gssh 'ls /dev/virtio-ports/ 2>/dev/null | tr "\n" " "' || true)"
  rec "      guest kernel: $(gssh 'uname -r' || true)"
  rec "      guest 9p support: $(gssh 'grep -c 9p /proc/filesystems || true' || true)"
  gssh 'sudo cp /bin/sleep /usr/local/bin/qemu-ga && sudo sh -c "nohup /usr/local/bin/qemu-ga 60 >/dev/null 2>&1 &"' >/dev/null 2>&1
  sleep 2
  NEG="$(gssh "ps -eo comm= | grep -cE '$AGENT_RE' || true" || true)"
  if [[ "${NEG:-0}" -ge 1 ]]; then PASS=$((PASS+1)); rec "PASS  negative-control: planted agent process detected (= $NEG)"
  else FAIL=$((FAIL+1)); rec "FAIL  negative-control: planted agent process NOT detected"; fi
  gssh 'sudo pkill -x qemu-ga; sudo rm -f /usr/local/bin/qemu-ga' >/dev/null 2>&1 || true
fi
pause "Enter to reboot and repeat."

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Reboot, then the verdict"
if [[ -n "$VM_IP" ]]; then
  run virsh reboot "$VM"
  sleep 10
  for _ in $(seq 1 60); do [[ "$(gssh hostname 2>/dev/null)" == "$VM" ]] && break; sleep 5; done
  check "readiness-probe-after-reboot" "200" \
    "$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "http://$URLHOST:$PROBE_PORT/lnrent-workload.conf")"
  check "host-keys-stable-across-reboot" "$KEYS" \
    "$(ssh-keyscan -T 5 "$VM_IP" 2>/dev/null | awk '$2 ~ /^(ssh-|ecdsa-|sk-)/ {print $2" "$3}' | sort -u | tr '\n' '|')"
  check "no-virtio-ports-after-reboot" "0" "$(gssh 'ls /dev/virtio-ports/ 2>/dev/null | wc -l')"
fi
rec "=== $PASS passed, $FAIL failed"
printf '\n'
if [[ "$FAIL" -eq 0 && -n "$VM_IP" ]]; then
  say "${BOLD}libvirt attaches no agent share and no agent channel.${RESET}"
  say "It built what the domain XML declared and nothing more, so a Box on this"
  say "backend CAN satisfy SEC-45's sentence as written, and the strong reading"
  say "of the tier-1 promise becomes available. That is the difference from Incus."
  F39_RESULT="libvirt-clean"
else
  say "${BOLD}$FAIL check(s) failed.${RESET} Read the transcript before concluding"
  say "anything: a failure here is as informative as a pass."
  F39_RESULT="libvirt-not-clean"
fi
write_env F39_RESULT "$F39_RESULT"
printf '\n'
if confirm "Destroy the domain $VM?"; then run virsh destroy "$VM"; run virsh undefine "$VM"; fi
note "transcript: $EVIDENCE"
finish
