//! Language-neutral conformance vectors (docs/protocol/README.md "Test vectors").
//!
//! `tests/vectors/*.json` is the byte-level contract a second implementation loads. This file
//! proves the Rust codec agrees with every fixture in both directions: decode the fixture, then
//! re-encode, and require the SAME JSON value — so a field the codec adds and the fixture lacks
//! fails (re-encode gains a key), and a field the fixture carries and the codec drops fails
//! (re-encode loses a key). A rename fails both ways. Every DM `type` must have a fixture and
//! every fixture must decode, so a new message type without a vector is a red test too.
//!
//! `listing.event.json` is a SIGNED kind-30402 event. It is parsed (signature verified) and
//! rebuilt; tags and content must match the fixture. Regenerate it with the ignored test at the
//! bottom when the listing layout changes on purpose.

use lnrent_wire::*;
use nostr::{Event, JsonUtil, Keys, Timestamp};
use serde_json::Value;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

fn vectors_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors")
}

fn read_json(name: &str) -> Value {
    let path = vectors_dir().join(name);
    let raw = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("{}: not JSON: {e}", path.display()))
}

/// The closed set of DM `type` discriminators is `Msg::ALL_TYPES`, generated by the same macro
/// that defines the enum and its serde renames — so a new variant is in the set by construction
/// and the assertion below demands a fixture for it. Nothing here is hand-maintained.
#[test]
fn every_dm_fixture_round_trips_to_the_same_json_value() {
    let mut seen_types = BTreeSet::new();
    let mut files = 0;
    for entry in std::fs::read_dir(vectors_dir()).expect("vectors dir") {
        let path = entry.expect("dir entry").path();
        let name = path.file_name().unwrap().to_string_lossy().into_owned();
        if !name.ends_with(".json") || name == "listing.event.json" {
            continue;
        }
        files += 1;
        let fixture = read_json(&name);
        let msg: Msg = serde_json::from_value(fixture.clone())
            .unwrap_or_else(|e| panic!("{name}: codec rejects the fixture: {e}"));
        assert_eq!(
            fixture["type"].as_str(),
            Some(msg.type_str()),
            "{name}: `type` discriminator vs the variant it decoded to"
        );
        let reencoded = serde_json::to_value(&msg).expect("encode");
        assert_eq!(
            reencoded, fixture,
            "{name}: decode->encode must reproduce the fixture exactly (no field gained, lost or renamed)"
        );
        seen_types.insert(msg.type_str());
    }
    assert!(
        files >= Msg::ALL_TYPES.len(),
        "expected at least one fixture per type, found {files} files"
    );
    let expected: BTreeSet<&str> = Msg::ALL_TYPES.iter().copied().collect();
    assert_eq!(
        seen_types, expected,
        "every Msg variant needs a fixture in tests/vectors/, and no fixture may carry an unlisted type"
    );
}

/// docs/protocol/dm-protocol.md §2 is the normative message catalogue. It and `Msg::ALL_TYPES`
/// must be the same set in both directions: a variant the table omits, or a row the enum lacks,
/// is a red test. Rows are recognised by their direction cell (`B→O` / `O→B` / `O→O`).
#[test]
fn protocol_doc_catalogue_matches_all_types() {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("../docs/protocol/dm-protocol.md");
    let doc = std::fs::read_to_string(&path).unwrap_or_else(|e| panic!("{}: {e}", path.display()));
    let documented: BTreeSet<&str> = doc
        .lines()
        .filter(|l| l.starts_with("| `"))
        .filter(|l| {
            ["| B→O |", "| O→B |", "| O→O |"]
                .iter()
                .any(|d| l.contains(d))
        })
        .map(|l| l.trim_start_matches("| `").split('`').next().unwrap())
        .collect();
    let enumerated: BTreeSet<&str> = Msg::ALL_TYPES.iter().copied().collect();
    assert_eq!(
        documented, enumerated,
        "dm-protocol.md §2 catalogue drifted from Msg::ALL_TYPES"
    );
}

/// The optional-field variants the spec calls out (dm-protocol.md §3.6, §3.7): a request-correlated
/// and an unsolicited `billing.invoice` / `billing.notice`. Pinned separately so the fixture set
/// cannot silently drop one of the two shapes.
#[test]
fn optional_request_id_variants_are_both_pinned() {
    assert!(read_json("billing.invoice.json")
        .get("request_id")
        .is_some());
    assert!(read_json("billing.invoice.auto.json")
        .get("request_id")
        .is_none());
    assert!(read_json("billing.notice.resuming.json")
        .get("request_id")
        .is_some());
    assert!(read_json("billing.notice.json").get("request_id").is_none());
    assert_eq!(read_json("op.result.ok.json")["status"], "ok");
    assert_eq!(read_json("op.result.error.json")["status"], "error");
}

/// The fixed operational key the listing vector is signed with. Test-only, publicly known.
const VECTOR_SECRET_HEX: &str = "7f3a1c5e9b2d4f60817a2b3c4d5e6f708192a3b4c5d6e7f8091a2b3c4d5e6f70";
const VECTOR_CREATED_AT: u64 = 1_757_376_000;

fn vector_listing() -> Listing {
    let keys = Keys::parse(VECTOR_SECRET_HEX).expect("vector key");
    Listing {
        d: "do-vps".into(),
        operator: keys.public_key().to_hex(),
        recipe_id: "do-vps".into(),
        recipe_version: "0.1.0".into(),
        title: "Cloud VPS (DigitalOcean)".into(),
        summary: "A dedicated cloud VPS with root SSH. 1 vCPU / 1 GB / 25 GB.".into(),
        amount_sat: 30000,
        period: "30d".into(),
        params: vec![ParamDecl {
            key: "ssh_pubkey".into(),
            label: "Your SSH public key".into(),
            ty: "string".into(),
            required: true,
        }],
        operations: vec![
            OperationDecl {
                name: "status".into(),
                label: "VPS status".into(),
                kind: "request".into(),
                params: vec![],
            },
            OperationDecl {
                name: "restart".into(),
                label: "Reboot the VPS".into(),
                kind: "request".into(),
                params: vec![],
            },
        ],
        tier: Some("0".into()),
        version: SCHEMA_VERSION,
    }
}

#[test]
fn listing_vector_parses_and_rebuilds_identically() {
    let raw = read_json("listing.event.json");
    let event = Event::from_json(raw.to_string()).expect("fixture is a nostr event");
    let parsed = parse_listing(&event).expect("signed 30402 fixture parses (signature verified)");

    let expected = vector_listing();
    assert_eq!(parsed.listing, expected, "parsed listing fields");
    assert_eq!(
        parsed.listing_id,
        listing_coordinate(&expected.operator, "do-vps"),
        "coordinate is 30402:<signer>:<d>"
    );

    // Rebuild from the parsed listing and require the SAME tags and content the fixture carries.
    // id/sig are not compared (Schnorr signatures are randomized), so the rebuilt event is signed
    // only to obtain a concrete Event to read tags from.
    let keys = Keys::parse(VECTOR_SECRET_HEX).unwrap();
    let rebuilt = build_listing(&parsed.listing)
        .expect("build")
        .custom_created_at(Timestamp::from(VECTOR_CREATED_AT))
        .sign_with_keys(&keys)
        .expect("sign");
    let fixture_tags: Vec<Vec<String>> = event.tags.iter().map(|t| t.clone().to_vec()).collect();
    let rebuilt_tags: Vec<Vec<String>> = rebuilt.tags.iter().map(|t| t.clone().to_vec()).collect();
    assert_eq!(rebuilt_tags, fixture_tags, "tag layout and order");
    let fixture_content: Value = serde_json::from_str(&event.content).unwrap();
    let rebuilt_content: Value = serde_json::from_str(&rebuilt.content).unwrap();
    assert_eq!(rebuilt_content, fixture_content, "content JSON");
}

/// Regenerator: `cargo test -p lnrent-wire --test vectors -- --ignored --nocapture
/// generate_listing_vector` prints the signed event; paste it into `tests/vectors/listing.event.json`.
/// Run it ONLY when the listing layout changes on purpose — that is a protocol change
/// (docs/protocol/listing.md).
#[test]
#[ignore]
fn generate_listing_vector() {
    let keys = Keys::parse(VECTOR_SECRET_HEX).unwrap();
    let event = build_listing(&vector_listing())
        .unwrap()
        .custom_created_at(Timestamp::from(VECTOR_CREATED_AT))
        .sign_with_keys(&keys)
        .unwrap();
    println!("{}", event.as_pretty_json());
}
